### ISSUE TITLE
spectrum panel: weird behaviour at the begining

### ISSUE THREAD

**Issue by fabienBourban** [mmlabs-mindmaze/mcpanel#3]
When you select a channel in the spectrum channel, the first second(s) give a crappy spectrum. 

Is this only due to the filter initialization?

**Comment by nbourdau** [comment]
This is indeed only due to spectrum initialization and there is little that can be done about it.

**Comment by rleeb** [comment]
I'm completely against  that this issue is closed it. It is an implementation bug. 
From a most probably wrong (zero) initialization of the fft buffer (even as mentioned by yourself on the tracker).

No other software in the world has this error. Please fix it. 
Just use the correct amount of data (and not zeros as I assume now) to initialize the buffer.  All the data is already in eegview available. Or wait to display the spectrum for the 1 second (or how long your buffer is)

Thanks

**Comment by nbourdau** [comment]
Commit open for review at https://review.gerrithub.io/c/mmlabs-mindmaze/mcpanel/+/499572
